import React from 'react';
import { motion } from 'framer-motion';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useInView } from 'react-intersection-observer';

const FAQ = () => {
    const { ref, inView } = useInView({ triggerOnce: true, threshold: 0.1 });
    
    const faqs = [
        { q: "What is digital marketing?", a: "Digital marketing encompasses all marketing efforts that use an electronic device or the internet. Businesses leverage digital channels such as search engines, social media, email, and their websites to connect with current and prospective customers." },
        { q: "How long does it take to see SEO results?", a: "SEO is a long-term strategy. While some results can be seen in as little as a few weeks, significant changes in rankings and organic traffic typically take 4-6 months to materialize, depending on the competition and the state of your website." },
        { q: "What is ROI in marketing?", a: "Return on Investment (ROI) in marketing measures the profit or revenue generated by a marketing campaign against the cost of that campaign. It's a key metric to determine the effectiveness and profitability of your marketing efforts." },
        { q: "Do you offer custom marketing packages?", a: "Absolutely! We understand that every business is unique. We offer custom packages tailored to your specific goals, budget, and industry. Contact us for a free consultation to discuss your needs." },
    ];
    
    return (
        <section ref={ref} id="faq" className="py-20 px-4 bg-emerald-950/20 simple-wave-bg">
            <div className="container mx-auto max-w-3xl">
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    animate={inView ? { opacity: 1, y: 0 } : {}}
                    transition={{ duration: 0.8 }}
                    className="text-center mb-12"
                >
                    <span className="text-lime-400 text-sm font-semibold mb-4 block">FAQ</span>
                    <h2 className="text-3xl md:text-5xl font-bold">Frequently Asked Questions</h2>
                </motion.div>
                
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={inView ? { opacity: 1 } : {}}
                    transition={{ duration: 0.5, delay: 0.2 }}
                >
                    <Accordion type="single" collapsible className="w-full space-y-4">
                        {faqs.map((faq, index) => (
                            <motion.div
                                key={index}
                                initial={{ opacity: 0, x: -50 }}
                                animate={inView ? { opacity: 1, x: 0 } : {}}
                                transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                            >
                                <AccordionItem value={`item-${index}`} className="bg-emerald-900/30 border border-emerald-800/50 rounded-lg px-6">
                                    <AccordionTrigger className="text-lg text-left font-semibold hover:no-underline">{faq.q}</AccordionTrigger>
                                    <AccordionContent className="text-gray-300 pt-2 pb-4">
                                        {faq.a}
                                    </AccordionContent>
                                </AccordionItem>
                            </motion.div>
                        ))}
                    </Accordion>
                </motion.div>
            </div>
        </section>
    );
};

export default FAQ;